import type { Metadata } from 'next'
import { ReactNode } from 'react'
import Sidebar from '~/components/sidebar'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='flex'>
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
